name: Overlay

on:
  workflow_dispatch:
    inputs:
      FORK_URL:
        description: 'FORKED_URL'
        required: true
        default: 'https://github.com/phhusson/vendor_hardware_overlay/tree/pie/Samsung/A51-SystemUI'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt -y install git-core git xmlstarlet
        sudo apt update

    - name: Clone vendor_hardware_overlay
      run: |
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        git clone ${{github.event.inputs.FORK_URL }}

    - name: Run test scripts
      run: |
        PATH=~/bin:$PATH
        cd workspace && cd vendor_hardware_overlay
        git config --global user.name "Johx22"
        git config --global user.email "johannjose2004@gmail.com"
        cd tests
        bash tests.sh

    - name: Build APK's
      run: |
        PATH=~/bin:$PATH
        cd workspace && cd vendor_hardware_overlay && cd build
        bash build.sh

    - name: Upload APK
      uses: actions/upload-artifact@v3.0.0
      with:
        path: workspace/vendor_hardware_overlay/build/*.apk
        name: Overlays
